# Generated by Django 2.2.8 on 2020-02-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=7)),
                ('street', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('ratings', models.CharField(max_length=5)),
                ('hotel_title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
