# Generated by Django 2.2.8 on 2020-02-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='ratings',
            field=models.FloatField(),
        ),
    ]
